// <auto-generated />
using System;
using MZ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MZ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MzDbContext))]
    partial class MzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MZ.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("ImieNazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaLogowania")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("OstatnieLogowanie")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rola")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NazwaLogowania")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataGodzina")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LaboratoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("LaboratoriumId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MZ.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Akcja")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataCzas")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Encja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncjaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaLogowania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stacja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzczegolyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UzytkownikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MZ.Domain.Entities.IndividualHealthPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DalszaDiagnostyka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DataPrzegladu")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataUtworzenia")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Interwencje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZaleceniaSzczepien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("HealthPlans");
                });

            modelBuilder.Entity("MZ.Domain.Entities.LabTestMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KodLab")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("LaboratoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TestDefinitionId");

                    b.HasIndex("LaboratoriumId", "KodLab")
                        .IsUnique();

                    b.ToTable("LabTestMappings");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Laboratory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("KonfiguracjaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontakt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypIntegracji")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("MZ.Domain.Entities.OrderedTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataZlecenia")
                        .HasColumnType("date");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Wymagane")
                        .HasColumnType("bit");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReferralId");

                    b.HasIndex("TestDefinitionId");

                    b.ToTable("OrderedTests");
                });

            modelBuilder.Entity("MZ.Domain.Entities.PackageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Wymagane")
                        .HasColumnType("bit");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TestDefinitionId");

                    b.HasIndex("TestPackageId");

                    b.ToTable("PackageItems");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataOstatniegoBilansu")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Plec")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ZgodaSms")
                        .HasColumnType("bit");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MZ.Domain.Entities.PipelineHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataPrzejscia")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusNa")
                        .HasColumnType("int");

                    b.Property<int?>("StatusZ")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("PipelineHistory");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ProgramEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataKwalifikacji")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataRozpoczecia")
                        .HasColumnType("date");

                    b.Property<string>("IdAnkietyKbzod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KoordynatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("MaBrakiBadan")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrzypisanyPakietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TerminKontaktu")
                        .HasColumnType("date");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KoordynatorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrzypisanyPakietId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CzynnikiRyzyka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataDecyzji")
                        .HasColumnType("date");

                    b.Property<int>("Decyzja")
                        .HasColumnType("int");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Uzasadnienie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UzytkownikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataWplywu")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataWypelnienia")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notatki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OcrPewnosc")
                        .HasColumnType("float");

                    b.Property<string>("OcrTekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScoringRuleSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkanPdfSciezka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusWeryfikacji")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Zrodlo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("ScoringRuleSetId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("MZ.Domain.Entities.QuestionnaireAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KodPytania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Wartosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireAnswers");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LaboratoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LekarzId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("LaboratoriumId");

                    b.HasIndex("LekarzId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataZaplanowana")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Wyslane")
                        .HasColumnType("bit");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CzynnikRyzyka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPytania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Punkty")
                        .HasColumnType("int");

                    b.Property<Guid>("ScoringRuleSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WartoscDopasowania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ScoringRuleSetId");

                    b.ToTable("ScoringRules");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ScoringRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ObowiazujeDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ObowiazujeOd")
                        .HasColumnType("date");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ScoringRuleSets");
                });

            modelBuilder.Entity("MZ.Domain.Entities.SignedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DataPodpisu")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlikSciezka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PodpisujacyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<int>("TypPodpisu")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PodpisujacyId");

                    b.ToTable("SignedDocuments");
                });

            modelBuilder.Entity("MZ.Domain.Entities.SmsMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BladOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DataWyslania")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentyfikatorBramki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SmsMessages");
                });

            modelBuilder.Entity("MZ.Domain.Entities.TestDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Jednostka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NormaMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NormaMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("TestDefinitions");
                });

            modelBuilder.Entity("MZ.Domain.Entities.TestPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ObowiazujeDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ObowiazujeOd")
                        .HasColumnType("date");

                    b.Property<int?>("Plec")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WiekMax")
                        .HasColumnType("int");

                    b.Property<int>("WiekMin")
                        .HasColumnType("int");

                    b.Property<string>("WymaganyCzynnikRyzyka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TestPackages");
                });

            modelBuilder.Entity("MZ.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataPobrania")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataWyniku")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Jednostka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LaboratoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OcenaNormy")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderedTestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurowyRekord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("WartoscLiczbowa")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WartoscTekstowa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Zrodlo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("LaboratoriumId");

                    b.HasIndex("OrderedTestId");

                    b.HasIndex("TestDefinitionId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CisnienieRozkurczowe")
                        .HasColumnType("int");

                    b.Property<int?>("CisnienieSkurczowe")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataWizyty")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ObwodTaliiCm")
                        .HasColumnType("float");

                    b.Property<Guid?>("PersonelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PodsumowanieWynikow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tetno")
                        .HasColumnType("int");

                    b.Property<string>("UtworzonoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("WagaKg")
                        .HasColumnType("float");

                    b.Property<double?>("WzrostCm")
                        .HasColumnType("float");

                    b.Property<string>("Zalecenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZmodyfikowanoPrzez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ZmodyfikowanoUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("PersonelId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithMany("Terminy")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.Laboratory", "Laboratorium")
                        .WithMany()
                        .HasForeignKey("LaboratoriumId");

                    b.HasOne("MZ.Domain.Entities.AppUser", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.Navigation("Enrollment");

                    b.Navigation("Laboratorium");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MZ.Domain.Entities.IndividualHealthPlan", b =>
                {
                    b.HasOne("MZ.Domain.Entities.Visit", "Visit")
                        .WithOne("Ipz")
                        .HasForeignKey("MZ.Domain.Entities.IndividualHealthPlan", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("MZ.Domain.Entities.LabTestMapping", b =>
                {
                    b.HasOne("MZ.Domain.Entities.Laboratory", "Laboratorium")
                        .WithMany("Mapowania")
                        .HasForeignKey("LaboratoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.TestDefinition", "TestDefinition")
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorium");

                    b.Navigation("TestDefinition");
                });

            modelBuilder.Entity("MZ.Domain.Entities.OrderedTest", b =>
                {
                    b.HasOne("MZ.Domain.Entities.Referral", "Referral")
                        .WithMany("Zlecone")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.TestDefinition", "TestDefinition")
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");

                    b.Navigation("TestDefinition");
                });

            modelBuilder.Entity("MZ.Domain.Entities.PackageItem", b =>
                {
                    b.HasOne("MZ.Domain.Entities.TestDefinition", "TestDefinition")
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.TestPackage", "TestPackage")
                        .WithMany("Pozycje")
                        .HasForeignKey("TestPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestDefinition");

                    b.Navigation("TestPackage");
                });

            modelBuilder.Entity("MZ.Domain.Entities.PipelineHistory", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithMany("Historia")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ProgramEnrollment", b =>
                {
                    b.HasOne("MZ.Domain.Entities.AppUser", "Koordynator")
                        .WithMany()
                        .HasForeignKey("KoordynatorId");

                    b.HasOne("MZ.Domain.Entities.Patient", "Patient")
                        .WithMany("Udzialy")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.TestPackage", "PrzypisanyPakiet")
                        .WithMany()
                        .HasForeignKey("PrzypisanyPakietId");

                    b.Navigation("Koordynator");

                    b.Navigation("Patient");

                    b.Navigation("PrzypisanyPakiet");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Qualification", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithOne("Kwalifikacja")
                        .HasForeignKey("MZ.Domain.Entities.Qualification", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.AppUser", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId");

                    b.Navigation("Enrollment");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Questionnaire", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithOne("Ankieta")
                        .HasForeignKey("MZ.Domain.Entities.Questionnaire", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.ScoringRuleSet", "ScoringRuleSet")
                        .WithMany()
                        .HasForeignKey("ScoringRuleSetId");

                    b.Navigation("Enrollment");

                    b.Navigation("ScoringRuleSet");
                });

            modelBuilder.Entity("MZ.Domain.Entities.QuestionnaireAnswer", b =>
                {
                    b.HasOne("MZ.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Referral", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithOne("Skierowanie")
                        .HasForeignKey("MZ.Domain.Entities.Referral", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.Laboratory", "Laboratorium")
                        .WithMany()
                        .HasForeignKey("LaboratoriumId");

                    b.HasOne("MZ.Domain.Entities.AppUser", "Lekarz")
                        .WithMany()
                        .HasForeignKey("LekarzId");

                    b.Navigation("Enrollment");

                    b.Navigation("Laboratorium");

                    b.Navigation("Lekarz");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("MZ.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Przypomnienia")
                        .HasForeignKey("AppointmentId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ScoringRule", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ScoringRuleSet", "ScoringRuleSet")
                        .WithMany("Reguly")
                        .HasForeignKey("ScoringRuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringRuleSet");
                });

            modelBuilder.Entity("MZ.Domain.Entities.SignedDocument", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.AppUser", "Podpisujacy")
                        .WithMany()
                        .HasForeignKey("PodpisujacyId");

                    b.Navigation("Enrollment");

                    b.Navigation("Podpisujacy");
                });

            modelBuilder.Entity("MZ.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithMany("Wyniki")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.Laboratory", "Laboratorium")
                        .WithMany()
                        .HasForeignKey("LaboratoriumId");

                    b.HasOne("MZ.Domain.Entities.OrderedTest", "OrderedTest")
                        .WithMany()
                        .HasForeignKey("OrderedTestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MZ.Domain.Entities.TestDefinition", "TestDefinition")
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Laboratorium");

                    b.Navigation("OrderedTest");

                    b.Navigation("TestDefinition");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Visit", b =>
                {
                    b.HasOne("MZ.Domain.Entities.ProgramEnrollment", "Enrollment")
                        .WithOne("Wizyta")
                        .HasForeignKey("MZ.Domain.Entities.Visit", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MZ.Domain.Entities.AppUser", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.Navigation("Enrollment");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Przypomnienia");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Laboratory", b =>
                {
                    b.Navigation("Mapowania");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Udzialy");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ProgramEnrollment", b =>
                {
                    b.Navigation("Ankieta");

                    b.Navigation("Historia");

                    b.Navigation("Kwalifikacja");

                    b.Navigation("Skierowanie");

                    b.Navigation("Terminy");

                    b.Navigation("Wizyta");

                    b.Navigation("Wyniki");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Questionnaire", b =>
                {
                    b.Navigation("Odpowiedzi");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Referral", b =>
                {
                    b.Navigation("Zlecone");
                });

            modelBuilder.Entity("MZ.Domain.Entities.ScoringRuleSet", b =>
                {
                    b.Navigation("Reguly");
                });

            modelBuilder.Entity("MZ.Domain.Entities.TestPackage", b =>
                {
                    b.Navigation("Pozycje");
                });

            modelBuilder.Entity("MZ.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Ipz");
                });
#pragma warning restore 612, 618
        }
    }
}
